[package]
name = "zkasper-committee-proof-guest"
version.workspace = true
edition.workspace = true

[lib]
name = "zkasper_committee_proof_guest"
path = "src/lib.rs"

[[bin]]
name = "zkasper-committee-proof-guest"
path = "src/main.rs"

[features]
default = []

[dependencies]
zkasper-common = { path = "../common", default-features = false }
ziskos = { workspace = true }
