//! Child program keys this guest was compiled against.
//!
//! Generated by `scripts/bake_child_vks.sh`. Edit that, not this.
//!
//! A key here is what makes recursion bind a *program* rather than whatever the
//! prover put in the witness. It is a constant because it has to be part of the
//! circuit: change it and this guest's ELF changes, which changes the key every
//! parent of this guest holds. `zkasper_common::recursion::UNSET_VK` — all
//! zeros — means the guest has never been baked, and since no program has that
//! key the circuit refuses every child proof until the script has run.

use zkasper_common::recursion::ProgramVk;

/// `zkasper-justification-guest`
pub const JUSTIFICATION_PROGRAM_VK: ProgramVk = [
    18190389716866650475,
    15570977105188299102,
    10271774781051341667,
    8543167455539231661,
];

/// `zkasper-epoch-diff-guest`
pub const EPOCH_DIFF_PROGRAM_VK: ProgramVk = [
    7172082185357583530,
    3170201351238257296,
    8344270706284046120,
    17984450014720544533,
];
