//! Child program keys this guest was compiled against.
//!
//! Generated by `scripts/bake_child_vks.sh`. Edit that, not this.
//!
//! A key here is what makes recursion bind a *program* rather than whatever the
//! prover put in the witness. It is a constant because it has to be part of the
//! circuit: change it and this guest's ELF changes, which changes the key every
//! parent of this guest holds. `zkasper_common::recursion::UNSET_VK` — all
//! zeros — means the guest has never been baked, and since no program has that
//! key the circuit refuses every child proof until the script has run.

use zkasper_common::recursion::ProgramVk;

/// `zkasper-aggregation-guest`
pub const AGGREGATE_PROGRAM_VK: ProgramVk = [
    5385490829655453486,
    562668016814776584,
    14143719550386224448,
    12251842284790132212,
];

/// `zkasper-justification-guest`
pub const JUSTIFICATION_PROGRAM_VK: ProgramVk = [
    10357851983192465984,
    6630297635568751579,
    7798269864833893964,
    1367063156312119371,
];
