//! Child program keys this guest was compiled against.
//!
//! Generated by `scripts/bake_child_vks.sh`. Edit that, not this.
//!
//! A key here is what makes recursion bind a *program* rather than whatever the
//! prover put in the witness. It is a constant because it has to be part of the
//! circuit: change it and this guest's ELF changes, which changes the key every
//! parent of this guest holds. `zkasper_common::recursion::UNSET_VK` — all
//! zeros — means the guest has never been baked, and since no program has that
//! key the circuit refuses every child proof until the script has run.

use zkasper_common::recursion::ProgramVk;

/// `zkasper-aggregation-guest`
pub const AGGREGATE_PROGRAM_VK: ProgramVk = [
    8434594428075584300,
    8150821444405656459,
    6083492043992368625,
    15434783641535826659,
];

/// `zkasper-justification-guest`
pub const JUSTIFICATION_PROGRAM_VK: ProgramVk = [
    16030659031914295012,
    2952940001647859397,
    12895666576665419187,
    5530306845015901616,
];
