//! Child program keys this guest was compiled against.
//!
//! Generated by `scripts/bake_child_vks.sh`. Edit that, not this.
//!
//! A key here is what makes recursion bind a *program* rather than whatever the
//! prover put in the witness. It is a constant because it has to be part of the
//! circuit: change it and this guest's ELF changes, which changes the key every
//! parent of this guest holds. `zkasper_common::recursion::UNSET_VK` — all
//! zeros — means the guest has never been baked, and since no program has that
//! key the circuit refuses every child proof until the script has run.

use zkasper_common::recursion::ProgramVk;

/// `zkasper-group-proof-guest`
pub const GROUP_PROGRAM_VK: ProgramVk = [
    11304595984233683776,
    2870753761926248207,
    4935412573429086103,
    6704949817305582921,
];

/// `zkasper-epoch-diff-guest`
pub const EPOCH_DIFF_PROGRAM_VK: ProgramVk = [
    6448522103961603108,
    15370524193848136874,
    13153090005201273888,
    3086649544714591617,
];

/// `zkasper-committee-proof-guest`
pub const COMMITTEE_PROGRAM_VK: ProgramVk = [
    7512518832490333510,
    491234436211134330,
    998073642685961050,
    8809244956387357866,
];
