//! Child program keys this guest was compiled against.
//!
//! Generated by `scripts/bake_child_vks.sh`. Edit that, not this.
//!
//! A key here is what makes recursion bind a *program* rather than whatever the
//! prover put in the witness. It is a constant because it has to be part of the
//! circuit: change it and this guest's ELF changes, which changes the key every
//! parent of this guest holds. `zkasper_common::recursion::UNSET_VK` — all
//! zeros — means the guest has never been baked, and since no program has that
//! key the circuit refuses every child proof until the script has run.

use zkasper_common::recursion::ProgramVk;

/// `zkasper-group-proof-guest`
pub const GROUP_PROGRAM_VK: ProgramVk = [
    3826119414262097977,
    6403585904935853484,
    12194850222198482096,
    14074009565910000795,
];

/// `zkasper-epoch-diff-guest`
pub const EPOCH_DIFF_PROGRAM_VK: ProgramVk = [
    9727264532793689080,
    13670888412280477661,
    4503673237683041309,
    4101011037470150902,
];

/// `zkasper-committee-proof-guest`
pub const COMMITTEE_PROGRAM_VK: ProgramVk = [
    15815920139138205262,
    10931602803380130733,
    17842208405794629951,
    12531133123712609239,
];
