//! Child program keys this guest was compiled against.
//!
//! Generated by `scripts/bake_child_vks.sh`. Edit that, not this.
//!
//! A key here is what makes recursion bind a *program* rather than whatever the
//! prover put in the witness. It is a constant because it has to be part of the
//! circuit: change it and this guest's ELF changes, which changes the key every
//! parent of this guest holds. `zkasper_common::recursion::UNSET_VK` — all
//! zeros — means the guest has never been baked, and since no program has that
//! key the circuit refuses every child proof until the script has run.

use zkasper_common::recursion::ProgramVk;

/// `zkasper-group-proof-guest`
pub const GROUP_PROGRAM_VK: ProgramVk = [
    12676793819134665246,
    5331889630329875880,
    13107491946224795289,
    14318552037566737118,
];

/// `zkasper-epoch-diff-guest`
pub const EPOCH_DIFF_PROGRAM_VK: ProgramVk = [
    3562539453701024840,
    9848632924983560442,
    11198755735979304140,
    6613259222763790048,
];

/// `zkasper-committee-proof-guest`
pub const COMMITTEE_PROGRAM_VK: ProgramVk = [
    18429873192332079175,
    12451676418547942331,
    4258710032247561582,
    9082684123376831256,
];
