[package]
name = "zkasper-fcr-verifier"
version.workspace = true
edition.workspace = true

[dependencies]
zkasper-common = { path = "../common", default-features = false }
zkasper-fcr-types = { path = "../fcr-types" }
fast_confirmation_core = { git = "https://github.com/dapplion/lighthouse.git", branch = "fcr-no-std" }
