#!/bin/bash
set -euo pipefail

# Build every guest ELF and bake each one's child keys into the guests that
# verify it.
#
# Usage: ./scripts/bake_child_vks.sh
#
# ---------------------------------------------------------------------------
# Why this exists
# ---------------------------------------------------------------------------
#
# A recursive verification checks a child proof against a key. If that key comes
# out of the witness it says only "this verifies under a key the prover chose",
# and a prover satisfies it by writing their own guest, proving whatever they
# like and handing over its key. The keys are therefore constants of the guests
# — `crates/*/src/child_vks.rs` — and this script is what writes them.
#
# ---------------------------------------------------------------------------
# Why the order is what it is, and why one pass is enough
# ---------------------------------------------------------------------------
#
# A key is derived from an ELF, and a constant is part of the ELF that holds it,
# so the keys form a dependency graph: change a guest and every guest that
# verifies it changes too. The graph is a DAG — nothing verifies its own
# descendants — so a topological pass reaches a fixed point without iterating:
#
#   1. epoch-diff, committee, slot-proof, group-proof   (no child keys at all)
#   2. aggregation      bakes group, epoch-diff, committee
#   3. justification    bakes slot          (its ELF also holds aggregation's, fixed at 2)
#   4. stream-final     bakes aggregate, justification
#   5. finalization     bakes justification, epoch-diff
#
# Nothing written at a later step can change an ELF built at an earlier one:
# `zkasper-common` holds no keys, and no guest named above depends on a crate
# whose `child_vks.rs` this script writes after building it. That is the whole
# reason the constants live in the guest crates rather than in one shared
# module — a shared module would put aggregation's key in a file aggregation
# itself compiles, and the graph would have a cycle with no fixed point.
#
# The three keys no step can bake are the ones a program would have to contain
# its own copy of: the justification, aggregate and stream-final fold chains.
# Those are published in the proof's public outputs instead; see
# `docs/finality/assumptions.md`, "Which program a child proof came from".
#
# ---------------------------------------------------------------------------
# What a mismatch looks like
# ---------------------------------------------------------------------------
#
# Every ELF the daemon loads is checked against these constants at startup, by
# `zkasper_witness_gen::child_vks::check` — in `ZiskProver` where the ELF is
# read, and again at the prover-server handshake. A guest that was never baked
# holds all zeros, which no program has, so it refuses every child proof rather
# than accepting one from anywhere.
#
# Rerun this after touching any guest, or any code a guest compiles in.

cd "$(dirname "$0")/.."
export PATH="${ZISK_BIN:-$HOME/.zisk/bin}:$PATH"

ELF_DIR=target/elf/riscv64ima-zisk-zkvm-elf/release
VK_BIN=${ZKASPER_VK_BIN:-target/release/zkasper-program-vk}
VKS=$(mktemp)
trap 'rm -f "$VKS"' EXIT

if [ ! -x "$VK_BIN" ]; then
  echo "=== building $VK_BIN ==="
  cargo build --release -p zkasper-witness-gen --features zisk-prover \
    --bin zkasper-program-vk
fi

build() {
  echo "=== building zkasper-$1 ==="
  cargo-zisk build --release -p "zkasper-$1"
}

# Derive the keys of the named guests, on one client, and remember them.
derive() {
  local elfs=()
  for guest in "$@"; do elfs+=("$ELF_DIR/zkasper-$guest"); done
  echo "=== deriving keys: $* ==="
  "$VK_BIN" "${elfs[@]}" >>"$VKS"
}

key() {
  local vk
  vk=$(awk -v elf="$ELF_DIR/zkasper-$1" '$1 == elf { print $2 }' "$VKS" | tail -1)
  [ -n "$vk" ] || { echo "no key derived for zkasper-$1" >&2; exit 1; }
  echo "${vk//,/, }"
}

# emit <file> [<const> <guest> <key>]...
emit() {
  local file=$1
  shift
  cat >"$file" <<'HEADER'
//! Child program keys this guest was compiled against.
//!
//! Generated by `scripts/bake_child_vks.sh`. Edit that, not this.
//!
//! A key here is what makes recursion bind a *program* rather than whatever the
//! prover put in the witness. It is a constant because it has to be part of the
//! circuit: change it and this guest's ELF changes, which changes the key every
//! parent of this guest holds. `zkasper_common::recursion::UNSET_VK` — all
//! zeros — means the guest has never been baked, and since no program has that
//! key the circuit refuses every child proof until the script has run.

use zkasper_common::recursion::ProgramVk;
HEADER
  while [ $# -gt 0 ]; do
    printf '\n/// `%s`\npub const %s: ProgramVk = [%s];\n' "$2" "$1" "$3" >>"$file"
    shift 3
  done
  # Four u64s on one line is over the width rustfmt wants, so a generated file
  # that is not formatted here fails `cargo fmt --check` the moment it is
  # committed -- and the next bake undoes whoever formatted it by hand.
  rustfmt --edition 2021 "$file" 2>/dev/null || true
  echo "wrote $file"
}

# 1. The leaves. Nothing they hold depends on anything this script writes.
for guest in epoch-diff-guest committee-proof-guest slot-proof-guest group-proof-guest; do
  build "$guest"
done
derive epoch-diff-guest committee-proof-guest slot-proof-guest group-proof-guest

# 2. Aggregation, which every other folding guest borrows its links from.
emit crates/aggregation-guest/src/child_vks.rs \
  GROUP_PROGRAM_VK zkasper-group-proof-guest "$(key group-proof-guest)" \
  EPOCH_DIFF_PROGRAM_VK zkasper-epoch-diff-guest "$(key epoch-diff-guest)" \
  COMMITTEE_PROGRAM_VK zkasper-committee-proof-guest "$(key committee-proof-guest)"
build aggregation-guest
derive aggregation-guest

# 3. Justification. Its ELF also holds aggregation's code, fixed above.
emit crates/justification-guest/src/child_vks.rs \
  SLOT_PROGRAM_VK zkasper-slot-proof-guest "$(key slot-proof-guest)"
build justification-guest
derive justification-guest

# 4. and 5. The two proofs a verifier consumes.
emit crates/stream-final-guest/src/child_vks.rs \
  AGGREGATE_PROGRAM_VK zkasper-aggregation-guest "$(key aggregation-guest)" \
  JUSTIFICATION_PROGRAM_VK zkasper-justification-guest "$(key justification-guest)"
build stream-final-guest

emit crates/finalization-guest/src/child_vks.rs \
  JUSTIFICATION_PROGRAM_VK zkasper-justification-guest "$(key justification-guest)" \
  EPOCH_DIFF_PROGRAM_VK zkasper-epoch-diff-guest "$(key epoch-diff-guest)"
build finalization-guest

derive stream-final-guest finalization-guest
echo
echo "=== keys ==="
cat "$VKS"
echo
echo "Commit the four crates/*/src/child_vks.rs files with the ELFs they describe."
