[package]
name = "zkasper-fcr-proof-guest"
version.workspace = true
edition.workspace = true

[[bin]]
name = "zkasper-fcr-proof-guest"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
zkasper-common = { path = "../common", default-features = false }
zkasper-fcr-types = { path = "../fcr-types" }
serde = { workspace = true }
bincode = { workspace = true }
ziskos = { workspace = true }
fast_confirmation_core = { git = "https://github.com/dapplion/lighthouse.git", branch = "fcr-no-std" }
