//! Child program keys this guest was compiled against.
//!
//! Generated by `scripts/bake_child_vks.sh`. Edit that, not this.
//!
//! A key here is what makes recursion bind a *program* rather than whatever the
//! prover put in the witness. It is a constant because it has to be part of the
//! circuit: change it and this guest's ELF changes, which changes the key every
//! parent of this guest holds. `zkasper_common::recursion::UNSET_VK` — all
//! zeros — means the guest has never been baked, and since no program has that
//! key the circuit refuses every child proof until the script has run.

use zkasper_common::recursion::ProgramVk;

/// `zkasper-slot-proof-guest`
pub const SLOT_PROGRAM_VK: ProgramVk = [
    12299888075674977259,
    350748356498297858,
    14245195355850231378,
    17951523003110983735,
];
